exclude: [nginx]
markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:title
rdiscount:
  extensions: [smart]
title : Niklas Lindblad
canonical: https://niklaslindblad.se
production_url : http://niklaslindblad.se
cloudfront_url : https://d2tjdh98vh6jzp.cloudfront.net
description: "MSE Nanoscience Engineering and freelance software developer"
disqus_shortname: nikaslindbladblog
analytics: UA-25940343-1
author :
  name : Niklas lindblad
  github : nlindblad
  twitter : nlindblad
  email: niklas@lindblad.info
